src/NewcomersTask.Web/Models/CancelOrderRequest.cs
// <copyright file="CancelOrderRequest.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewcomersTask.Web.Models
{
    public class CancelOrderRequest
    {
        public Guid OrderId { get; set; }
    }
}

src/NewcomersTask.Web/Models/ChangedOrderStatusRequest.cs
// <copyright file="ChangedOrderStatusRequest.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using NewcomersTask.Models;

namespace NewcomersTask.Web.Models
{
    public class ChangedOrderStatusRequest
    {
        public Guid OrderId { get; set; }

        public Status Status { get; set; }
    }
}

src/NewcomersTask.Web/Models/CreateOrderRequest.cs
// <copyright file="CreateOrderRequest.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewcomersTask.Web.Models
{
    public class CreateOrderRequest
    {
        public int OrderNumber { get; set; }

        public DateTime OrderDate { get; set; }

        public string? CustomerName { get; set; }

        public string? CustomerSurname { get; set; }

        public List<OrderItemRequest>? OrderSagaItems { get; set; }
    }
}

src/NewcomersTask.Web/Models/OrderCreateRequest.cs
namespace NewcomersTask.Web.Models
{
    public class OrderCreateRequest
    {
        public int OrderNumber { get; set; }

        public DateTime OrderDate { get; set; }

        public string? CustomerName { get; set; }

        public string? CustomerSurname { get; set; }

        public List<OrderItemRequest>? OrderSagaItems { get; set; }
    }
}

src/NewcomersTask.Web/Models/OrderItemRequest.cs
// <copyright file="OrderItemRequest.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace NewcomersTask.Web.Models
{
    public class OrderItemRequest
    {
        public string? Sku { get; set; }

        public decimal Price { get; set; }

        public int Quantity { get; set; }
    }
}

src/NewcomersTask.Web/Controllers/OrderSagaController.cs
// <copyright file="OrderSagaController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using AutoMapper;
using MassTransit;
using Microsoft.AspNetCore.Mvc;
using NewcomersTask.Models;
using NewcomersTask.Web.Models;

namespace NewcomersTask.Web.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class OrderSagaController : ControllerBase
    {
        private readonly IBus _bus;
        private readonly IMapper _mapper;
        private readonly ILogger<OrderSagaController> _logger;

        public OrderSagaController(
            IBus bus,
            IMapper mapper,
            ILogger<OrderSagaController> logger)
        {
            _bus = bus;
            _mapper = mapper;
            _logger = logger;
        }

        [HttpPost("create")]
        public async Task CreateAsync([FromForm] CreateOrderRequest model)
        {
            _logger.LogInformation("Start!");
            var request = _mapper.Map<OrderCreated>(model);
            request.OrderId = Guid.NewGuid();
            var endpoint = await _bus.GetSendEndpoint(new Uri("exchange:order-state?bind=true&queue=order-state"));
            await endpoint.Send(request);

            _logger.LogInformation("End!");
        }

        [HttpPost("update")]
        public async Task StatusChangedAsync([FromForm] ChangedOrderStatusRequest model)
        {
            _logger.LogInformation("Start!");

            var request = _mapper.Map<OrderStatusChanged>(model);
            var endpoint = await _bus.GetSendEndpoint(new Uri("exchange:order-state?bind=true&queue=order-state"));
            await endpoint.Send(request);

            _logger.LogInformation("End!");
        }

        [HttpPost("cancel")]
        public async Task StatusChangedAsync([FromForm] CancelOrderRequest model)
        {
            _logger.LogInformation("Start!");

            var request = _mapper.Map<OrderCancelled>(model);
            var endpoint = await _bus.GetSendEndpoint(new Uri("exchange:order-state?bind=true&queue=order-state"));
            await endpoint.Send(request);

            _logger.LogInformation("End!");
        }
    }
}

src/NewcomersTask.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace NewcomersTask.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/NewcomersTask.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewcomersTask.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/NewcomersTask.Web/Pages/OrderSaga/Cancel.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NewcomersTask.Web.Models;

namespace NewcomersTask.Web.Pages.OrderSaga;

public class Cancel : PageModel
{
    private readonly ILogger<Cancel> _logger;

    public Cancel(ILogger<Cancel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }

    public CancelOrderRequest Model { get; set; }

    public void OnPost(CancelOrderRequest report)
    {
    }
}

src/NewcomersTask.Web/Pages/OrderSaga/Create.cshtml.cs
// <copyright file="Create.cshtml.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewcomersTask.Web.Pages;

public class Create : PageModel
{
    private readonly ILogger<Create> _logger;

    public Create(ILogger<Create> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

src/NewcomersTask.Web/Pages/OrderSaga/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewcomersTask.Web.Pages;

public class Update : PageModel
{
    private readonly ILogger<Update> _logger;

    public Update(ILogger<Update> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

src/NewcomersTask.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewcomersTask.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/NewcomersTask.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/NewcomersTask.Web/Pages/OrderSaga/Cancel.cshtml
@page
@using NewcomersTask.Web.Models
@model Cancel
@using (Html.BeginForm("cancel", "OrderSaga", FormMethod.Post))
{
    
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="2" align="center">Order</th>
        </tr>
        <tr>
            <td>Order number: </td>
            <td>
                @Html.TextBoxFor(m => m.Model.OrderId)
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit"  /></td>
        </tr>
    </table>
}

src/NewcomersTask.Web/Pages/OrderSaga/Create.cshtml
@page
@using NewcomersTask.Web.Models
@model CreateOrderRequest
@using (Html.BeginForm("create", "OrderSaga", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="2" align="center">Order</th>
        </tr>
        <tr>
            <td>Order number: </td>
            <td>
                @Html.TextBoxFor(m => m.OrderNumber, new { type = "number", min = "0", step = "1" })
            </td>
        </tr>
        <tr>
            <td>OrderDate: </td>
            <td>
                @Html.EditorFor(model => model.OrderDate)
                @Html.ValidationMessageFor(model => model.OrderDate)
            </td>
        </tr>
        <tr>
            <td>Customer name: </td>
            <td>
                @Html.TextBoxFor(m => m.CustomerName)
            </td>
        </tr>
        <tr>
            <td>Customer surname: </td>
            <td>
                @Html.TextBoxFor(m => m.CustomerSurname)
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit" /></td>
        </tr>
    </table>
    <script>
        $(function () {
            $("#OrderDate").datepicker();
        });
    </script>
}

src/NewcomersTask.Web/Pages/OrderSaga/Update.cshtml
@page
@using NewcomersTask.Web.Models
@model ChangedOrderStatusRequest
@using (Html.BeginForm("update", "OrderSaga", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="2" align="center">Update order</th>
        </tr>
        <tr>
            <td>OrderId: </td>
            <td>
                @Html.TextBoxFor(m => m.OrderId)
            </td>
        </tr>
        <tr>
            <td>Status: </td>
            <td>
                @Html.DropDownList("Status",  Html.GetEnumSelectList<NewcomersTask.Models.Status>(), "Select Status", new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit" /></td>
        </tr>
    </table>
}

src/NewcomersTask.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewcomersTask.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NewcomersTask.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">NewcomersTask.Web</a>
                <a class="navbar-brand" asp-area="" asp-page="/OrderSaga/create">Create</a>
                <a class="navbar-brand" asp-area="" asp-page="/OrderSaga/update">Update</a>
                <a class="navbar-brand" asp-area="" asp-page="/OrderSaga/cancel">Cancel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NewcomersTask.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>